### ISSUE TITLE
Snake 2.1 bug

### ISSUE THREAD

**Issue by ZZcat** [leoxiong-zzz/Casio-fx-9750GII#1]
Snake bug:
Ever time to time your a is go off the screen, it isn't invisible ether.

**Comment by ZZcat** [comment]
Snake bug:
Your numbers disappear when i go over them

**Comment by leoxiong-zzz** [comment]
Yeah, I'm aware that the apple goes off screen once in a while... Unfortunately I don't have a fix for it at the moment. If I remember correctly it's caused when the snake erases it's tail where the new apple spawned all in one frame.

The score is only drawn when you eat the apple. Saves a Locate instruction running each frame.
